import {objects} from './assets/objects.mjs';
import {levels} from './levels.mjs';
import {createRun,tick,find,miss,hint,stars,pause,resume,validateRun,dailyPick} from './engine.mjs';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],KEY='canal-town-v1',W=1536,H=1024,byId=Object.fromEntries(objects.map(o=>[o.id,o])),icon=id=>`<svg viewBox="0 0 80 80" aria-hidden="true"><use href="assets/objects.svg#${id}"></use></svg>`;
let run=null,level=null,inGame=false,sound=false,audio=null,book={found:[],best:{},daily:[]},view={zoom:1,x:0,y:0,fit:1},last=performance.now(),lastSave=0,hintId=null,hintEnd=0,resumeAfterModal=false,saveWarn=false,suppressUntil=0,gesture=null;const pointers=new Map();
function day(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function save(){try{if(run)run.savedAt=Date.now();localStorage.setItem(KEY,JSON.stringify({run,book,sound}))}catch{if(!saveWarn){saveWarn=true;toast('此瀏覽器無法儲存，仍可繼續遊玩。')}}}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(!s)return;run=validateRun(s.run,levels);if(run?.status==='playing')pause(run);if(s.book){book.found=Array.isArray(s.book.found)?[...new Set(s.book.found.filter(x=>byId[x]))]:[];book.daily=Array.isArray(s.book.daily)?s.book.daily.filter(x=>/^\d{4}-\d\d-\d\d$/.test(x)).slice(-366):[];for(const l of levels){let n=s.book.best?.[l.id];if(Number.isInteger(n)&&n>=1&&n<=3)book.best[l.id]=n}}sound=s.sound===true}catch{run=null}}
function tone(win=false){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const t=audio.currentTime;[523,659,...(win?[784,1046]:[])].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(0,t+i*.09);g.gain.linearRampToValueAtTime(.07,t+i*.09+.02);g.gain.exponentialRampToValueAtTime(.001,t+i*.09+.35);o.start(t+i*.09);o.stop(t+i*.09+.4)})}catch{}}
function soundUI(){$('#sound-btn').textContent=`音效 ${sound?'開':'關'}`;$('#sound-btn').setAttribute('aria-pressed',String(sound))}
function homeUI(){$('#continue-btn').hidden=!run||!['playing','paused'].includes(run.status);$('#collection-count').textContent=`${book.found.length} / ${objects.length}`;$('#level-cards').innerHTML=levels.map(l=>`<button class="level-card" data-level="${l.id}" aria-label="開始${l.name}"><div class="cover" style="background-image:url('${l.image}')"><span class="chapter-tag">${l.chapter}</span></div><div class="card-text"><h3>${l.name}</h3><p>${l.description}</p><span class="card-stars" aria-label="最佳${book.best[l.id]||0}星">${'★'.repeat(book.best[l.id]||0)}${'☆'.repeat(3-(book.best[l.id]||0))}</span></div></button>`).join('');all('[data-level]').forEach(b=>b.onclick=()=>requestStart(b.dataset.level));$('#daily-date').textContent=day().replaceAll('-',' / ')+' · 每日小品';$('#daily-status').textContent=book.daily.includes(day())?'今日已拾完 · 再逛一次 ↗':'開始今日漫遊 ↗';soundUI()}
function home(){if(run?.status==='playing')pause(run);inGame=false;$('#game').hidden=true;$('#home').hidden=false;history.replaceState(null,'',location.pathname+location.search);save();homeUI();window.scrollTo(0,0)}
function modal(html){resumeAfterModal=inGame&&run?.status==='playing';if(resumeAfterModal){pause(run);save();stats()}$('#modal-content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function closeModal(restore=true){$('#modal').close();if(restore&&resumeAfterModal&&inGame&&run?.status==='paused'){resume(run);last=performance.now();stats()}resumeAfterModal=false;save()}
function requestStart(id,daily=false){if(run&&['playing','paused'].includes(run.status)){modal('<p class="eyebrow">換一條巷，換一段風景</p><h2 class="modal-title">開始新的漫遊？</h2><p>尚未找完的進度會被替換。已收藏的小物與星星都會保留。</p><div class="modal-actions"><button class="primary" id="confirm-new">開始新的漫遊</button><button class="secondary" id="cancel-new">保留目前進度</button></div>');$('#confirm-new').onclick=()=>{closeModal(false);start(id,daily)};$('#cancel-new').onclick=()=>closeModal()}else start(id,daily)}
function start(id,daily=false){const p=daily?dailyPick(day(),levels):null;level=levels.find(l=>l.id===(p?.levelId||id));run=createRun({levelId:level.id,mode:daily?'relaxed':$('#mode').value,dailyKey:daily?day():null,targetIds:p?.targetIds||level.targets.map(t=>t.id)});mount();save()}
function mount(){level=levels.find(l=>l.id===run.levelId);inGame=true;$('#home').hidden=true;$('#game').hidden=false;if(location.hash!=='#play')history.pushState(null,'','#play');$('#chapter-label').textContent=run.dailyKey?'一日一尋 · '+run.dailyKey:level.chapter;$('#scene-title').textContent=level.name;$('#mode-label').textContent=run.dailyKey?'每日 · 不限時':run.mode==='challenge'?'挑戰 · 三分鐘':'休閒 · 不限時';$('#load-status').hidden=false;$('#load-status').textContent='畫卷展開中…';const img=$('#scene-image');img.alt=level.name+'：'+level.description;img.onload=()=>{$('#load-status').hidden=true;layout();last=performance.now()};img.onerror=()=>{$('#load-status').textContent='畫卷未能載入，請重新整理再試。';pause(run);stats()};img.src=level.image;if(img.complete&&img.naturalWidth)$('#load-status').hidden=true;$('#targets-layer').innerHTML=level.targets.filter(t=>run.targetIds.includes(t.id)).map(t=>`<button class="object-target" data-object="${t.id}" aria-label="尋找${byId[t.id].name}" style="left:${t.x}px;top:${t.y}px;width:${t.size}px;height:${t.size}px">${icon(t.id)}</button>`).join('');all('[data-object]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(performance.now()<suppressUntil)return;collect(b.dataset.object)});$('#target-list').innerHTML=run.targetIds.map(id=>`<div class="target-card" data-card="${id}">${icon(id)}<span>${byId[id].name}</span></div>`).join('');view={zoom:innerWidth<700?2.1:1,x:0,y:0,fit:1};hintId=null;$('#feedback').textContent='依清單的插畫造型找小物；拖曳探索畫卷兩側。';last=performance.now();foundUI();stats();layout();window.scrollTo(0,0);$('#viewport').focus({preventScroll:true})}
function collect(id){if(run?.status!=='playing'||$('#modal').open||!$('#load-status').hidden)return;tickNow();if(!find(run,id))return;if(!book.found.includes(id))book.found.push(id);$('#feedback').textContent=`找到了，${byId[id].name}！${byId[id].story}`;hintId=null;tone(run.status==='won');foundUI();stats();save();if(run.status==='won')finish()}
function foundUI(){if(!run)return;all('[data-object]').forEach(b=>{const f=run.found.includes(b.dataset.object);b.classList.toggle('found',f);b.classList.toggle('hinted',b.dataset.object===hintId);b.disabled=f;b.setAttribute('aria-label',`${f?'已找到':'尋找'}${byId[b.dataset.object].name}`)});all('[data-card]').forEach(c=>{const f=run.found.includes(c.dataset.card);c.classList.toggle('found',f);c.setAttribute('aria-label',byId[c.dataset.card].name+'，'+(f?'已找到':'尚未找到'))});$('#progress').textContent=`${run.found.length} / ${run.targetIds.length}`;$('#progress-bar').style.width=run.found.length/run.targetIds.length*100+'%';$('#collection-count').textContent=`${book.found.length} / ${objects.length}`}
function time(ms){let n=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function stats(){if(!run)return;$('#timer').textContent=time(run.mode==='challenge'?180000-run.elapsedMs:run.elapsedMs);$('#timer').style.color=run.mode==='challenge'&&run.elapsedMs>150000?'#b4533c':'';$('#paused-overlay').hidden=run.status!=='paused';$('#targets-layer').inert=run.status!=='playing';$('#pause-btn').textContent=run.status==='paused'?'繼續':'暫停';$('#pause-btn').disabled=!['playing','paused'].includes(run.status);const wait=Math.max(0,Math.ceil((run.nextHintAt-run.elapsedMs)/1000));$('#hint-btn').disabled=run.status!=='playing'||wait>0;$('#hint-btn').innerHTML=`借一盞明燈 <span>${wait?wait+' 秒後':'提示'}</span>`;$('#hint-note').textContent=`已借 ${run.hints} 次明燈 · 誤點 ${run.misses} 次`}
function tickNow(){const now=performance.now(),delta=now-last;last=now;if(run?.status==='playing'&&inGame&&!document.hidden&&$('#load-status').hidden){tick(run,delta);if(run.status==='lost'){save();finish()}}}
function frame(){tickNow();if(inGame&&run){stats();if(hintId&&performance.now()>hintEnd){hintId=null;foundUI()}if(run.status==='playing'&&performance.now()-lastSave>1500){lastSave=performance.now();save()}}requestAnimationFrame(frame)}
function finish(){if(run.status==='won'){book.best[run.levelId]=Math.max(book.best[run.levelId]||0,stars(run));if(run.dailyKey&&!book.daily.includes(run.dailyKey))book.daily.push(run.dailyKey);save();const next=levels[(levels.findIndex(l=>l.id===run.levelId)+1)%levels.length];modal(`<p class="eyebrow">畫卷收好，故事留下</p><h2 class="modal-title">${level.name} · 尋物完成</h2><div class="win-stars" aria-label="${stars(run)}星">${'★'.repeat(stars(run))}${'☆'.repeat(3-stars(run))}</div><p>${level.story}</p><div class="win-stats"><span>用時 ${time(run.elapsedMs)}</span><span>提示 ${run.hints} 次</span><span>誤點 ${run.misses} 次</span></div><p class="modal-sub">已收藏 ${book.found.length} / ${objects.length} 件小物。</p><div class="modal-actions"><button id="next-level" class="primary">前往${next.name} ↗</button><button id="replay" class="secondary">重遊這一卷</button><button id="result-home" class="secondary">返回古鎮</button></div>`);$('#next-level').onclick=()=>{closeModal(false);start(next.id)}}else{modal(`<p class="eyebrow">三分鐘，留下一點意猶未盡</p><h2 class="modal-title">茶歇時間到了</h2><p>這次找到 ${run.found.length} / ${run.targetIds.length} 件。已發現的小物都已收藏。</p><div class="modal-actions"><button id="relax-retry" class="primary">不限時再逛</button><button id="replay" class="secondary">再挑戰一次</button><button id="result-home" class="secondary">返回古鎮</button></div>`);$('#relax-retry').onclick=()=>{const id=run.levelId;closeModal(false);$('#mode').value='relaxed';start(id)}}$('#replay').onclick=()=>{const id=run.levelId,d=!!run.dailyKey,m=run.mode;closeModal(false);$('#mode').value=m;start(id,d)};$('#result-home').onclick=()=>{closeModal(false);home()}}
function collection(){modal(`<p class="eyebrow">COLLECTION · ${book.found.length} / ${objects.length}</p><h2 class="modal-title">古鎮藏物冊</h2><p class="modal-sub">每件小物，都藏著一段日常。找到它，就能讀它的故事。</p><div class="collection-grid">${objects.map(o=>{const h=book.found.includes(o.id);return `<div class="collection-item ${h?'':'locked'}">${icon(o.id)}<h3>${h?o.name:'尚待發現'}</h3><p>${h?o.story:'漫遊三卷畫境，尋回這段故事。'}</p></div>`}).join('')}</div>`)}
function help(){modal('<p class="eyebrow">拾光小箋</p><h2 class="modal-title">尋常日子，也有寶藏。</h2><ol class="help-list"><li>依清單的插畫造型點選同樣的小物；背景中的一般擺設不計分。</li><li>拖曳探索，滾輪或雙指縮放。按「全景」可看完整畫卷。</li><li>借明燈會移到一件小物，畫上虛線圈。每次等 15 秒就能再用。</li><li>休閒／每日不限時；挑戰三分鐘。暫停、離開或切換分頁都會停止計時。</li><li>三星：提示 0 次、誤點不超過 3 次。二星：提示不超過 2 次、誤點不超過 10 次。全部找到至少一星。</li><li>自動保存在此瀏覽器。重開後按「繼續上次漫遊」；清除瀏覽資料也會清除進度。</li><li>鍵盤：Tab 選小物、Enter 尋找。畫卷上方向鍵移動、＋／− 縮放、0 看全景。</li></ol>')}
function layout(){if(!inGame)return;view.fit=Math.min($('#viewport').clientWidth/W,$('#viewport').clientHeight/H);apply()}
function apply(){const el=$('#viewport'),vw=el.clientWidth,vh=el.clientHeight,s=view.fit*view.zoom,bx=Math.max(0,(W*s-vw)/2),by=Math.max(0,(H*s-vh)/2);view.x=Math.max(-bx,Math.min(bx,view.x));view.y=Math.max(-by,Math.min(by,view.y));$('#world').style.transform=`translate(${(vw-W*s)/2+view.x}px,${(vh-H*s)/2+view.y}px) scale(${s})`;$('#zoom-label').textContent=Math.round(view.zoom*100)+'%';$('#zoom-out').disabled=view.zoom<=1;$('#zoom-in').disabled=view.zoom>=4}
function zoom(f,a){const el=$('#viewport'),old=view.zoom,n=Math.max(1,Math.min(4,old*f));if(a){const x=a.x-el.clientWidth/2,y=a.y-el.clientHeight/2;view.x=x-(x-view.x)*n/old;view.y=y-(y-view.y)*n/old}else{view.x*=n/old;view.y*=n/old}view.zoom=n;apply()}
function center(id){const t=level.targets.find(t=>t.id===id);view.zoom=Math.max(2.1,view.zoom);view.x=(W/2-t.x)*view.fit*view.zoom;view.y=(H/2-t.y)*view.fit*view.zoom;apply()}
const vp=$('#viewport');vp.addEventListener('pointerdown',e=>{if(run?.status!=='playing'||!$('#load-status').hidden||e.button>0)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)gesture={sx:e.clientX,sy:e.clientY,x:view.x,y:view.y,moved:false};else if(pointers.size===2){const[a,b]=[...pointers.values()];gesture={pinch:true,d:Math.hypot(a.x-b.x,a.y-b.y),z:view.zoom,x:view.x,y:view.y,mx:(a.x+b.x)/2,my:(a.y+b.y)/2,moved:true};suppressUntil=performance.now()+400}});vp.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&gesture.pinch){const[a,b]=[...pointers.values()];view.zoom=Math.max(1,Math.min(4,gesture.z*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,gesture.d)));view.x=gesture.x+(a.x+b.x)/2-gesture.mx;view.y=gesture.y+(a.y+b.y)/2-gesture.my;apply();suppressUntil=performance.now()+400}else if(!gesture.pinch){const x=e.clientX-gesture.sx,y=e.clientY-gesture.sy;if(Math.hypot(x,y)>7){gesture.moved=true;vp.setPointerCapture(e.pointerId);view.x=gesture.x+x;view.y=gesture.y+y;apply();suppressUntil=performance.now()+400}}});function pointerEnd(e){if(gesture?.moved)suppressUntil=performance.now()+400;pointers.delete(e.pointerId);if(pointers.size===1){const a=[...pointers.values()][0];gesture={sx:a.x,sy:a.y,x:view.x,y:view.y,moved:true}}else gesture=null}vp.addEventListener('pointerup',pointerEnd);vp.addEventListener('pointercancel',pointerEnd);vp.addEventListener('lostpointercapture',e=>{pointers.delete(e.pointerId);if(!pointers.size)gesture=null});vp.addEventListener('click',e=>{if(e.target.closest('.object-target,#paused-overlay')||run?.status!=='playing'||performance.now()<suppressUntil||!$('#load-status').hidden)return;miss(run);$('#feedback').textContent='這裡還不是要找的小物。看看清單的造型，慢慢來。';stats();save()});vp.addEventListener('wheel',e=>{if(run?.status!=='playing')return;e.preventDefault();const r=vp.getBoundingClientRect();zoom(e.deltaY<0?1.15:1/1.15,{x:e.clientX-r.left,y:e.clientY-r.top})},{passive:false});vp.addEventListener('keydown',e=>{if(e.target!==vp||run?.status!=='playing')return;const k=e.key;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','0'].includes(k))e.preventDefault();if(k==='ArrowLeft')view.x+=60;if(k==='ArrowRight')view.x-=60;if(k==='ArrowUp')view.y+=60;if(k==='ArrowDown')view.y-=60;if(k==='+'||k==='=')zoom(1.2);else if(k==='-')zoom(1/1.2);else if(k==='0'){view.zoom=1;view.x=view.y=0}apply()});
$('#zoom-in').onclick=()=>zoom(1.25);$('#zoom-out').onclick=()=>zoom(1/1.25);$('#reset-view').onclick=()=>{view.zoom=1;view.x=view.y=0;apply()};$('#hint-btn').onclick=()=>{if(run?.status!=='playing')return;tickNow();const id=hint(run);if(!id)return;hintId=id;hintEnd=performance.now()+6500;center(id);foundUI();stats();$('#feedback').textContent=`明燈照向「${byId[id].name}」，找找虛線圈內的小物。`;save()};function togglePause(){if(run?.status==='playing'){tickNow();pause(run)}else if(run?.status==='paused'){resume(run);last=performance.now()}stats();save()}
$('#pause-btn').onclick=togglePause;$('#resume-btn').onclick=togglePause;$('#exit-btn').onclick=home;$('#home-link').onclick=e=>{e.preventDefault();home()};$('#start-btn').onclick=()=>requestStart('canal');$('#daily-btn').onclick=()=>requestStart(null,true);$('#continue-btn').onclick=()=>{if(run){mount();if(run.status==='paused')togglePause()}};$('#collection-btn').onclick=collection;$('#help-btn').onclick=help;$('#sound-btn').onclick=()=>{sound=!sound;soundUI();save();if(sound)tone()};$('#close-modal').onclick=()=>closeModal();$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeModal()});window.addEventListener('resize',layout);document.addEventListener('visibilitychange',()=>{if(document.hidden&&run?.status==='playing'){pause(run);stats();save()}last=performance.now()});window.addEventListener('pagehide',()=>{if(run?.status==='playing')pause(run);save()});window.addEventListener('popstate',()=>{if(inGame)home()});load();homeUI();if(location.hash)history.replaceState(null,'',location.pathname+location.search);requestAnimationFrame(frame);
