export const CHALLENGE_LIMIT_MS=180000,HINT_COOLDOWN_MS=15000;
export function createRun({levelId,mode='relaxed',dailyKey=null,targetIds,now=Date.now()}){return {version:1,levelId,mode,dailyKey,targetIds:[...targetIds],found:[],elapsedMs:0,hints:0,misses:0,nextHintAt:0,status:'playing',savedAt:now}}
export function tick(r,delta){if(r.status!=='playing'||!Number.isFinite(delta))return;r.elapsedMs=Math.min(r.mode==='challenge'?CHALLENGE_LIMIT_MS:Number.MAX_SAFE_INTEGER,r.elapsedMs+Math.max(0,delta));if(r.mode==='challenge'&&r.elapsedMs>=CHALLENGE_LIMIT_MS)r.status='lost'}
export function find(r,id){if(r.status!=='playing'||!r.targetIds.includes(id)||r.found.includes(id))return false;r.found.push(id);if(r.found.length===r.targetIds.length)r.status='won';return true}
export function miss(r){if(r.status==='playing')r.misses++}
export function hint(r){if(r.status!=='playing'||r.elapsedMs<r.nextHintAt)return null;const id=r.targetIds.find(id=>!r.found.includes(id));if(!id)return null;r.hints++;r.nextHintAt=r.elapsedMs+HINT_COOLDOWN_MS;return id}
export function stars(r){return r.status!=='won'?0:r.hints===0&&r.misses<=3?3:r.hints<=2&&r.misses<=10?2:1}
export function pause(r){if(r.status!=='playing')return false;r.status='paused';return true}
export function resume(r){if(r.status!=='paused')return false;r.status='playing';return true}
const validDate=s=>typeof s==='string'&&/^\d{4}-\d\d-\d\d$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
export function validateRun(v,levels){try{const r=typeof v==='string'?JSON.parse(v):v;if(!r||r.version!==1||!['relaxed','challenge'].includes(r.mode)||!['playing','paused','won','lost'].includes(r.status))return null;const l=levels.find(l=>l.id===r.levelId);if(!l)return null;for(const k of ['targetIds','found'])if(!Array.isArray(r[k])||r[k].length!==new Set(r[k]).size||r[k].some(id=>typeof id!=='string'||!l.targets.some(t=>t.id===id)))return null;if(!r.targetIds.length||r.found.some(id=>!r.targetIds.includes(id)))return null;for(const k of ['elapsedMs','hints','misses','nextHintAt','savedAt'])if(!Number.isFinite(r[k])||r[k]<0||r[k]>Number.MAX_SAFE_INTEGER)return null;if(!Number.isInteger(r.hints)||!Number.isInteger(r.misses))return null;if(r.dailyKey!==null&&!validDate(r.dailyKey))return null;if(r.status==='won'&&r.found.length!==r.targetIds.length)return null;if(r.status!=='won'&&r.found.length===r.targetIds.length)return null;if(r.mode==='challenge'&&(r.elapsedMs>CHALLENGE_LIMIT_MS||(r.status==='lost')!==(r.elapsedMs===CHALLENGE_LIMIT_MS)))return null;if(r.status==='lost'&&r.mode!=='challenge')return null;return {...r,targetIds:[...r.targetIds],found:[...r.found]}}catch{return null}}
export function dailyPick(date,levels){if(!validDate(date)||!levels.length)throw Error('Invalid daily puzzle');let seed=[...date].reduce((a,c)=>(Math.imul(a,31)+c.charCodeAt(0))>>>0,7);const rnd=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296};const sorted=[...levels].sort((a,b)=>a.id.localeCompare(b.id)),l=sorted[Math.floor(rnd()*sorted.length)],ids=l.targets.map(t=>t.id).sort();for(let i=ids.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}return {levelId:l.id,targetIds:ids.slice(0,6)}}
